Update precision generation rules
ecrc/ecrc_cmake pull request #6
Opened 2022-11-01 07:58 UTC by MernaMoawad

2022-11-01 08:01 UTC, SAbdulah commented
@MernaMoawad, more description about the changes, please!

2022-11-01 08:35 UTC, MernaMoawad commented
1. Updated the syntax to be python-3 friendly.
2. Chmod command was removed because it was locking the files and then blocking the building with multiple processes(Rules Precision.cmake)
3.  Add additional support for python-2
4. expanded some variables holding commands to avoid inaccurate separators added.

2022-11-01 08:36 UTC, ltaiefhatem requested changes

2022-11-01 08:36 UTC, ltaiefhatem commented on modules/RulesPrecisions.cmake
> +          CACHE INTERNAL "Dictionnary used for precision generation" )
please remove these spaces so that they do not appear as changes

2022-11-01 08:36 UTC, ltaiefhatem commented on modules/RulesPrecisions.cmake
> +          CACHE INTERNAL "Dictionnary used for precision generation" )
spaces

2022-11-01 08:36 UTC, ltaiefhatem commented on modules/RulesPrecisions.cmake
> +          CACHE INTERNAL "Set of available precisions for the project" )
spaces, please remove the subsequent ones too

2022-11-01 08:38 UTC, ltaiefhatem commented
> * Updated the syntax to be python-3 friendly.
> * Chmod command was removed because it was locking the files and then blocking the building with multiple processes(Rules Precision.cmake)
> * Add additional support for python-2
> * expanded some variables holding commands to avoid inaccurate separators added.

I am not familiar with the changes but happy to acknowledge the changes needed to support various python versions.
Have u tested it on various python versions? on Jenkins?

2022-11-01 09:41 UTC, ltaiefhatem requested changes

2022-11-01 09:41 UTC, ltaiefhatem commented on modules/RulesPrecisions.cmake
> +  set(RP_${CMAKE_PROJECT_NAME}_DICTIONNARY ${ECRC_CMAKE_MODULE_PATH}/precision_generator/subs.py
good catch!

2022-11-01 09:41 UTC, ltaiefhatem commented on modules/RulesPrecisions.cmake
> +      CACHE INTERNAL "Dictionnary used for precision generation" )
still spaces... check the diffs to identify them

2022-11-01 09:41 UTC, ltaiefhatem commented on modules/RulesPrecisions.cmake
> -	set(generate_out 1)
space vs tab?

2022-11-01 09:41 UTC, ltaiefhatem commented on modules/RulesPrecisions.cmake
> +        string(COMPARE NOTEQUAL "${_dependency_OUTPUT}" "${_dependency_INPUT}" generate_out )
space vs tab

2022-11-07 07:38 UTC, ltaiefhatem approved these changes
Looks good

2022-11-28 15:12 UTC, SAbdulah approved these changes
It seems most of the changes not major. I am approving this!

2022-11-29 12:52 UTC, merged